name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    env:
      TAG: ${{ github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set Docker image tag
        id: set_tag
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "TAG=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "TAG=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build . -t ephimeral-dev

      - name: Tag Docker image

        run: docker tag ephimeral-dev ${{ secrets.DOCKERHUB_USERNAME }}/ephimeral-dev:${{env.TAG}}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ephimeral-dev:${{env.TAG}}

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/ephimeral-dev:latest
