name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: Build the Docker image
      run: docker build . -t ephimeral-dev:latest
      
    - name: Push to Docker Hub
      run: docker push kalbekalu/ephimeral-dev:latest
